version: '3.8'
services:
  postgres:
    container_name: postgres-project3
    image: postgres:14.1
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - project3-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  project3-data: